/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fastfoodmanagement;

import common.OpenPDF;
import dao.BillDao;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Bill;

/**
 *
 * @author Admin
 */
public class Revenue extends javax.swing.JFrame {

    /**
     * Creates new form Revenue
     */
    public Revenue() {
        initComponents();

    }

//    public void tableDetail() {
//        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//        String date1 = sdf.format(chooserDate1.getDate());
//        String date2 = sdf.format(chooserDate2.getDate());
//
//        DefaultTableModel dtm = (DefaultTableModel) tableRevenue.getModel();
//        dtm.setRowCount(0);
//        ArrayList<Bill> list = BillDao.getRevenue(date1);
//        Iterator<Bill> itr = list.iterator();
//        while (itr.hasNext()) {
//            Bill billObj = itr.next();
//            dtm.addRow(new Object[]{billObj.getId(), billObj.getName(), billObj.getMobileNumber(), billObj.getDate(), billObj.getTotal(), billObj.getCreateBy()});
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. T he content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRevenue = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        chooserDate1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        chooserDate2 = new com.toedter.calendar.JDateChooser();
        btnClose = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtRevenue = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-revenue-48.png"))); // NOI18N
        jLabel1.setText("REVENUE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 200, 58));

        tableRevenue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mobile Number", "Date", "Total", "Create By"
            }
        ));
        tableRevenue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRevenueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableRevenue);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 965, 400));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Từ ngày");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, 22));
        getContentPane().add(chooserDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 200, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Đến ngày");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, -1, 20));
        getContentPane().add(chooserDate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 201, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-close-48.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(2835, 0, 40, 40));

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 160, 80, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("Tổng doanh thu ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 780, -1, -1));

        txtRevenue.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtRevenue.setForeground(new java.awt.Color(255, 255, 255));
        txtRevenue.setText("000");
        getContentPane().add(txtRevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 680, 120, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("        REVENUE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 680, 130, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background1.jpeg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableRevenueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRevenueMouseClicked
        // TODO add your handling code here:
        int index = tableRevenue.getSelectedRow();
        TableModel model = tableRevenue.getModel();
        String id = model.getValueAt(index, 0).toString();
        OpenPDF.openById(id);
    }//GEN-LAST:event_tableRevenueMouseClicked

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        double revenueTotal = 0;
        DefaultTableModel dtm = (DefaultTableModel) tableRevenue.getModel();
        ArrayList<Bill> list = BillDao.getAllRecords();
        Iterator<Bill> itr = list.iterator();
        while (itr.hasNext()) {
            Bill billObj = itr.next();
            dtm.addRow(new Object[]{billObj.getId(), billObj.getName(), billObj.getMobileNumber(), billObj.getDate(), billObj.getTotal(), billObj.getCreateBy()});
            revenueTotal += Double.parseDouble(billObj.getTotal());
        }
        txtRevenue.setText(String.valueOf(revenueTotal));
    }//GEN-LAST:event_formComponentShown

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        double revenueTotal = 0;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date1 = sdf.format(chooserDate1.getDate());
        String date2 = sdf.format(chooserDate2.getDate());

        DefaultTableModel dtm = (DefaultTableModel) tableRevenue.getModel();
        dtm.setRowCount(0);
        ArrayList<Bill> list = BillDao.getRevenue(date1, date2);
        Iterator<Bill> itr = list.iterator();
        while (itr.hasNext()) {
            Bill billObj = itr.next();
            dtm.addRow(new Object[]{billObj.getId(), billObj.getName(), billObj.getMobileNumber(), billObj.getDate(), billObj.getTotal(), billObj.getCreateBy()});
            revenueTotal += Double.parseDouble(billObj.getTotal());
        }
        txtRevenue.setText(String.valueOf(revenueTotal));
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Revenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Revenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Revenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Revenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Revenue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnOk;
    private com.toedter.calendar.JDateChooser chooserDate1;
    private com.toedter.calendar.JDateChooser chooserDate2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRevenue;
    private javax.swing.JLabel txtRevenue;
    // End of variables declaration//GEN-END:variables
}
